//Fetching
export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';

//Quiz
export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const QUIZ_FINISH = 'QUIZ_FINISH';
export const QUIZ_NEXT_QUIESTION = 'QUIZ_NEXT_QUIESTION';
export const QUIZ_RETRY = 'QUIZ_RETRY';

//QuizCreator
export const QUIZ_CREATE_QUESTION = 'QUIZ_CREATE_QUESTION';
export const QUIZ_CREATION_RESET = 'QUIZ_CREATION_RESET';

//Auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
